# Generated by Django 4.0.2 on 2022-02-18 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='searchflights',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dep_airport', models.CharField(max_length=20)),
                ('ar_airport', models.CharField(max_length=20)),
                ('cls_name', models.CharField(max_length=20)),
                ('Journey_date', models.DateField()),
                ('no_passengers', models.IntegerField()),
            ],
        ),
    ]
