# Generated by Django 4.0.2 on 2022-02-18 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fly', '0002_flights'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flights',
            name='id',
        ),
        migrations.AlterField(
            model_name='flights',
            name='flight_name',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
