# Generated by Django 4.0.2 on 2022-02-18 15:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fly', '0003_remove_flights_id_alter_flights_flight_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='searchflights',
            old_name='ar_airport',
            new_name='arr_airport',
        ),
        migrations.CreateModel(
            name='Roots',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dep_airport', models.CharField(max_length=50)),
                ('dep_time', models.TimeField()),
                ('arr_airport', models.CharField(max_length=50)),
                ('arr_time', models.TimeField()),
                ('travel_time', models.DurationField(blank=True, null=True)),
                ('cls', models.CharField(choices=[('Economy Class', 'Economy Class'), ('Business Class', 'Business Class'), ('First Class', 'First Class')], max_length=50)),
                ('total_fare', models.IntegerField()),
                ('flight_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fly.flights')),
            ],
        ),
        migrations.CreateModel(
            name='ConfirmBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=50)),
                ('address', models.TextField()),
                ('vaccine', models.CharField(max_length=50)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=50)),
                ('totalfare', models.IntegerField()),
                ('flight_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fly.flights')),
                ('journey_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fly.roots')),
            ],
        ),
    ]
