# Generated by Django 4.0.2 on 2022-02-21 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fly', '0004_rename_ar_airport_searchflights_arr_airport_roots_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='confirmbooking',
            name='flight_name',
        ),
    ]
