# Generated by Django 4.0.2 on 2022-02-21 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fly', '0005_remove_confirmbooking_flight_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='searchflights',
        ),
    ]
