# Generated by Django 4.0.2 on 2022-02-27 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fly', '0007_confirmbooking_journey_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='confirmbooking',
            name='passenger',
            field=models.IntegerField(default=4),
            preserve_default=False,
        ),
    ]
